/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import main.BaseDatos;
import main.Main;

/**
 *
 * @author Miguel
 */
public class creacionOfertas extends javax.swing.JFrame {
    

    /**
     * Creates new form creacionOfertas
     */
    public creacionOfertas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        navbar = new javax.swing.JPanel();
        navbarTxt = new javax.swing.JLabel();
        exitB = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        oferta = new javax.swing.JPanel();
        crearOfertaB = new javax.swing.JPanel();
        crearOfertaLabel = new javax.swing.JLabel();
        valorViviendaBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        salirB = new javax.swing.JPanel();
        salirLabel = new javax.swing.JLabel();
        tipoContratoBox = new javax.swing.JComboBox<>();
        ingresosTotalesBox = new javax.swing.JComboBox<>();
        aporteMaximoBox = new javax.swing.JComboBox<>();
        descOfertaScroll = new javax.swing.JScrollPane();
        descOferta = new javax.swing.JTextArea();
        nombreOferta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1130, 628));
        setUndecorated(true);
        setResizable(false);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navbar.setBackground(new java.awt.Color(0, 255, 153));
        navbar.setMaximumSize(new java.awt.Dimension(1130, 570));
        navbar.setPreferredSize(new java.awt.Dimension(1130, 72));

        navbarTxt.setFont(new java.awt.Font("Tw Cen MT", 0, 48)); // NOI18N
        navbarTxt.setForeground(new java.awt.Color(255, 255, 255));
        navbarTxt.setText("hipoteka");
        navbarTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        navbarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navbarTxtMouseClicked(evt);
            }
        });

        exitB.setBackground(new java.awt.Color(0, 255, 153));

        exitTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBLayout = new javax.swing.GroupLayout(exitB);
        exitB.setLayout(exitBLayout);
        exitBLayout.setHorizontalGroup(
            exitBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );
        exitBLayout.setVerticalGroup(
            exitBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
        navbar.setLayout(navbarLayout);
        navbarLayout.setHorizontalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(navbarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 791, Short.MAX_VALUE)
                .addComponent(exitB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        navbarLayout.setVerticalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(navbarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(navbarLayout.createSequentialGroup()
                .addComponent(exitB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        fondo.add(navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        oferta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crearOfertaB.setBackground(new java.awt.Color(255, 255, 255));

        crearOfertaLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        crearOfertaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crearOfertaLabel.setText("Crear oferta");
        crearOfertaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearOfertaLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout crearOfertaBLayout = new javax.swing.GroupLayout(crearOfertaB);
        crearOfertaB.setLayout(crearOfertaBLayout);
        crearOfertaBLayout.setHorizontalGroup(
            crearOfertaBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crearOfertaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        crearOfertaBLayout.setVerticalGroup(
            crearOfertaBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crearOfertaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        oferta.add(crearOfertaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 470, 100, 40));

        valorViviendaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<100.000 €", "<200.000 €", "<300.000 €", ">300.000 €" }));
        valorViviendaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorViviendaBoxActionPerformed(evt);
            }
        });
        oferta.add(valorViviendaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 126, 50));

        jLabel2.setText("Valor de la vivienda:");
        oferta.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 116, 50));

        jLabel3.setText("Tipo de contrato: ");
        oferta.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 100, 50));

        jLabel4.setText("Aporte máximo:");
        oferta.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 90, 50));

        jLabel5.setText("Ingresos totales:");
        oferta.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 90, 50));

        salirLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        salirLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salirLabel.setText("X");
        salirLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout salirBLayout = new javax.swing.GroupLayout(salirB);
        salirB.setLayout(salirBLayout);
        salirBLayout.setHorizontalGroup(
            salirBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salirBLayout.createSequentialGroup()
                .addComponent(salirLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        salirBLayout.setVerticalGroup(
            salirBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, salirBLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(salirLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        oferta.add(salirB, new org.netbeans.lib.awtextra.AbsoluteConstraints(848, 0, 40, -1));

        tipoContratoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indefinido", "Temporal", "Autónomo", "Otros" }));
        oferta.add(tipoContratoBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 126, 50));

        ingresosTotalesBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<1.000 €", "<3.000 €", ">3.000 €" }));
        oferta.add(ingresosTotalesBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 126, 50));

        aporteMaximoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<50.000 €", "<100.000 €", ">100.000 €" }));
        oferta.add(aporteMaximoBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 126, 50));

        descOferta.setColumns(20);
        descOferta.setRows(5);
        descOfertaScroll.setViewportView(descOferta);

        oferta.add(descOfertaScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 830, 200));

        nombreOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreOfertaActionPerformed(evt);
            }
        });
        oferta.add(nombreOferta, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 240, 40));

        jLabel1.setText("Nombre de la oferta:");
        oferta.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        fondo.add(oferta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 890, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void navbarTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navbarTxtMouseClicked
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_navbarTxtMouseClicked

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitB.setBackground(Color.RED);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitB.setBackground(new Color(0, 255, 153));
    }//GEN-LAST:event_exitTxtMouseExited

    private void valorViviendaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorViviendaBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorViviendaBoxActionPerformed

    private void crearOfertaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearOfertaLabelMouseClicked
        if(descOferta.getText().isBlank() || nombreOferta.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "Debe añadir una descripción.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(descOferta.getText().length() < 50){
            JOptionPane.showMessageDialog(this, "Deben de haber al menos 50 caracteres.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(nombreOferta.getText().length() > 25){
            JOptionPane.showMessageDialog(this, "El nombre debe ser más corto.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            
            String valorVivienda = valorViviendaBox.getSelectedItem().toString();
            String tipoContrato = tipoContratoBox.getSelectedItem().toString();
            String salario = ingresosTotalesBox.getSelectedItem().toString();
            String aporteMaximo = aporteMaximoBox.getSelectedItem().toString();
            
            BaseDatos.getInstance().crearOferta(Main.getIntance().getBanco().getId(), valorVivienda, tipoContrato, salario, aporteMaximo, descOferta.getText(), nombreOferta.getText());
            
            this.dispose();
            vPBanco vPB = new vPBanco();
            vPB.setVisible(true);
            
        }
        
    }//GEN-LAST:event_crearOfertaLabelMouseClicked

    private void salirLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirLabelMouseClicked
        this.dispose();
        vPBanco vPB = new vPBanco();
        vPB.setVisible(true);
    }//GEN-LAST:event_salirLabelMouseClicked

    private void nombreOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreOfertaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreOfertaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(creacionOfertas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(creacionOfertas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(creacionOfertas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(creacionOfertas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new creacionOfertas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> aporteMaximoBox;
    private javax.swing.JPanel crearOfertaB;
    private javax.swing.JLabel crearOfertaLabel;
    private javax.swing.JTextArea descOferta;
    private javax.swing.JScrollPane descOfertaScroll;
    private javax.swing.JPanel exitB;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JPanel fondo;
    private javax.swing.JComboBox<String> ingresosTotalesBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel navbar;
    private javax.swing.JLabel navbarTxt;
    private javax.swing.JTextField nombreOferta;
    private javax.swing.JPanel oferta;
    private javax.swing.JPanel salirB;
    private javax.swing.JLabel salirLabel;
    private javax.swing.JComboBox<String> tipoContratoBox;
    private javax.swing.JComboBox<String> valorViviendaBox;
    // End of variables declaration//GEN-END:variables
}
