/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import main.Main;

/**
 *
 * @author Miguel
 */
public class form4 extends javax.swing.JFrame {
    
    Color colorP = new Color(0, 0, 51);

    /**
     * Creates new form form
     */
    public form4() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarImagenes();
    }
    
    public void cargarImagenes(){

        ImageIcon imgThisImg = new ImageIcon("C:\\Users\\Miguel\\Documents\\NetBeansProjects\\hipoteka\\src\\main\\java\\imagenes\\Picsart_24-02-28_19-12-02-305.jpg");
        imgFondo.setIcon(imgThisImg);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        navbar = new javax.swing.JPanel();
        navbarTxt = new javax.swing.JLabel();
        exitB = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        panelQ = new javax.swing.JPanel();
        sigB = new javax.swing.JPanel();
        sigTxt = new javax.swing.JLabel();
        preguntaTxt = new javax.swing.JLabel();
        sigB3 = new javax.swing.JPanel();
        sigTxt3 = new javax.swing.JLabel();
        sigB4 = new javax.swing.JPanel();
        sigTxt4 = new javax.swing.JLabel();
        sigB5 = new javax.swing.JPanel();
        sigTxt5 = new javax.swing.JLabel();
        sigB6 = new javax.swing.JPanel();
        sigTxt6 = new javax.swing.JLabel();
        sigB7 = new javax.swing.JPanel();
        sigTxt7 = new javax.swing.JLabel();
        imgFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1130, 628));
        setUndecorated(true);
        setResizable(false);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setMaximumSize(new java.awt.Dimension(1130, 628));
        fondo.setMinimumSize(new java.awt.Dimension(1130, 628));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navbar.setBackground(new java.awt.Color(0, 255, 153));
        navbar.setMaximumSize(new java.awt.Dimension(1130, 570));

        navbarTxt.setFont(new java.awt.Font("Tw Cen MT", 0, 48)); // NOI18N
        navbarTxt.setForeground(new java.awt.Color(255, 255, 255));
        navbarTxt.setText("hipoteka");
        navbarTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        navbarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navbarTxtMouseClicked(evt);
            }
        });

        exitB.setBackground(new java.awt.Color(0, 255, 153));

        exitTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBLayout = new javax.swing.GroupLayout(exitB);
        exitB.setLayout(exitBLayout);
        exitBLayout.setHorizontalGroup(
            exitBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );
        exitBLayout.setVerticalGroup(
            exitBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
        navbar.setLayout(navbarLayout);
        navbarLayout.setHorizontalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(navbarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 791, Short.MAX_VALUE)
                .addComponent(exitB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        navbarLayout.setVerticalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(navbarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(navbarLayout.createSequentialGroup()
                .addComponent(exitB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        fondo.add(navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 72));

        panelQ.setBackground(new java.awt.Color(255, 255, 255));
        panelQ.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 1, true));

        sigB.setBackground(new java.awt.Color(255, 255, 255));
        sigB.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 1, true));
        sigB.setForeground(new java.awt.Color(0, 255, 153));

        sigTxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        sigTxt.setForeground(new java.awt.Color(0, 0, 51));
        sigTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sigTxt.setText(">");
        sigTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sigTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sigTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sigTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout sigBLayout = new javax.swing.GroupLayout(sigB);
        sigB.setLayout(sigBLayout);
        sigBLayout.setHorizontalGroup(
            sigBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sigTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );
        sigBLayout.setVerticalGroup(
            sigBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sigTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        preguntaTxt.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        preguntaTxt.setForeground(new java.awt.Color(0, 0, 51));
        preguntaTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        preguntaTxt.setText("¿Qué tipo de contrato tienes?");

        sigB3.setBackground(new java.awt.Color(255, 255, 255));
        sigB3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 1, true));
        sigB3.setForeground(new java.awt.Color(0, 255, 153));

        sigTxt3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        sigTxt3.setForeground(new java.awt.Color(0, 0, 51));
        sigTxt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sigTxt3.setText("<");
        sigTxt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sigTxt3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sigTxt3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sigTxt3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout sigB3Layout = new javax.swing.GroupLayout(sigB3);
        sigB3.setLayout(sigB3Layout);
        sigB3Layout.setHorizontalGroup(
            sigB3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sigTxt3, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );
        sigB3Layout.setVerticalGroup(
            sigB3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sigTxt3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        sigB4.setBackground(new java.awt.Color(255, 255, 255));
        sigB4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 1, true));
        sigB4.setForeground(new java.awt.Color(0, 255, 153));

        sigTxt4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sigTxt4.setForeground(new java.awt.Color(0, 0, 51));
        sigTxt4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sigTxt4.setText("Indefinido");
        sigTxt4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sigTxt4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sigTxt4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sigTxt4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout sigB4Layout = new javax.swing.GroupLayout(sigB4);
        sigB4.setLayout(sigB4Layout);
        sigB4Layout.setHorizontalGroup(
            sigB4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sigTxt4, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
        );
        sigB4Layout.setVerticalGroup(
            sigB4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sigTxt4, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        sigB5.setBackground(new java.awt.Color(255, 255, 255));
        sigB5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 1, true));
        sigB5.setForeground(new java.awt.Color(0, 255, 153));

        sigTxt5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sigTxt5.setForeground(new java.awt.Color(0, 0, 51));
        sigTxt5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sigTxt5.setText("Temporal");
        sigTxt5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sigTxt5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sigTxt5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sigTxt5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout sigB5Layout = new javax.swing.GroupLayout(sigB5);
        sigB5.setLayout(sigB5Layout);
        sigB5Layout.setHorizontalGroup(
            sigB5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sigTxt5, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
        );
        sigB5Layout.setVerticalGroup(
            sigB5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sigTxt5, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        sigB6.setBackground(new java.awt.Color(255, 255, 255));
        sigB6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 1, true));
        sigB6.setForeground(new java.awt.Color(0, 255, 153));

        sigTxt6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sigTxt6.setForeground(new java.awt.Color(0, 0, 51));
        sigTxt6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sigTxt6.setText("Autónomo");
        sigTxt6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sigTxt6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sigTxt6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sigTxt6MouseExited(evt);
            }
        });

        javax.swing.GroupLayout sigB6Layout = new javax.swing.GroupLayout(sigB6);
        sigB6.setLayout(sigB6Layout);
        sigB6Layout.setHorizontalGroup(
            sigB6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sigTxt6, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
        );
        sigB6Layout.setVerticalGroup(
            sigB6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sigTxt6, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        sigB7.setBackground(new java.awt.Color(255, 255, 255));
        sigB7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 1, true));
        sigB7.setForeground(new java.awt.Color(0, 255, 153));

        sigTxt7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sigTxt7.setForeground(new java.awt.Color(0, 0, 51));
        sigTxt7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sigTxt7.setText("Otros");
        sigTxt7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sigTxt7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sigTxt7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sigTxt7MouseExited(evt);
            }
        });

        javax.swing.GroupLayout sigB7Layout = new javax.swing.GroupLayout(sigB7);
        sigB7.setLayout(sigB7Layout);
        sigB7Layout.setHorizontalGroup(
            sigB7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sigTxt7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sigB7Layout.setVerticalGroup(
            sigB7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sigTxt7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelQLayout = new javax.swing.GroupLayout(panelQ);
        panelQ.setLayout(panelQLayout);
        panelQLayout.setHorizontalGroup(
            panelQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQLayout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(panelQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(preguntaTxt)
                    .addGroup(panelQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelQLayout.createSequentialGroup()
                            .addComponent(sigB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(220, 220, 220)
                            .addComponent(sigB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelQLayout.createSequentialGroup()
                            .addGroup(panelQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelQLayout.createSequentialGroup()
                                    .addComponent(sigB4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelQLayout.createSequentialGroup()
                                    .addComponent(sigB6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)))
                            .addGroup(panelQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(sigB5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sigB7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(85, 85, 85))
        );
        panelQLayout.setVerticalGroup(
            panelQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelQLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(preguntaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sigB4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sigB5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sigB6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sigB7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(panelQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sigB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sigB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        fondo.add(panelQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, 400));
        fondo.add(imgFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 72, 1130, 556));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void navbarTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navbarTxtMouseClicked
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_navbarTxtMouseClicked

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered

        exitB.setBackground(Color.RED);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitB.setBackground(new Color(0, 255, 153));
    }//GEN-LAST:event_exitTxtMouseExited

    private void sigTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sigTxtMouseClicked
        
        Boolean cancelar = false;
        
        if(sigB4.getBackground().equals(colorP)){
            Main.getIntance().getUsuarioActivo().setContrato(sigTxt4.getText());
        }
        else if(sigB5.getBackground().equals(colorP)){
            Main.getIntance().getUsuarioActivo().setContrato(sigTxt5.getText());
        }
        else if(sigB6.getBackground().equals(colorP)){
            Main.getIntance().getUsuarioActivo().setContrato(sigTxt6.getText());
        }
        else if(sigB7.getBackground().equals(colorP)){
            Main.getIntance().getUsuarioActivo().setContrato(sigTxt7.getText());
        }
        else{
            cancelar = true;
        }
      
        if(cancelar == true){
            JOptionPane.showMessageDialog(this, "Seleccione una opcion", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            this.dispose();
            form5 q5 = new form5();
            q5.setVisible(true);
        }
    }//GEN-LAST:event_sigTxtMouseClicked

    private void sigTxt4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sigTxt4MouseClicked
        
        sigB4.setBackground(new Color(0, 0, 51));
        sigTxt4.setForeground(Color.WHITE);
      
        if(sigB5.getBackground().equals(colorP)){
            sigB5.setBackground(Color.WHITE);
            sigTxt5.setForeground(new Color(0, 0, 51));
        }
        else if(sigB6.getBackground().equals(colorP)){
            sigB6.setBackground(Color.WHITE);
            sigTxt6.setForeground(new Color(0, 0, 51));
        }
        else if(sigB7.getBackground().equals(colorP)){
            sigB7.setBackground(Color.WHITE);
            sigTxt7.setForeground(new Color(0, 0, 51));
        }
        
    }//GEN-LAST:event_sigTxt4MouseClicked

    private void sigTxt5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sigTxt5MouseClicked
        
        sigB5.setBackground(new Color(0, 0, 51));
        sigTxt5.setForeground(Color.WHITE);
      
        if(sigB7.getBackground().equals(colorP)){
            sigB7.setBackground(Color.WHITE);
            sigTxt7.setForeground(new Color(0, 0, 51));
        }
        else if(sigB6.getBackground().equals(colorP)){
            sigB6.setBackground(Color.WHITE);
            sigTxt6.setForeground(new Color(0, 0, 51));
        }
        else if(sigB4.getBackground().equals(colorP)){
            sigB4.setBackground(Color.WHITE);
            sigTxt4.setForeground(new Color(0, 0, 51));
        }
        
    }//GEN-LAST:event_sigTxt5MouseClicked

    private void sigTxt6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sigTxt6MouseClicked
        
        sigB6.setBackground(new Color(0, 0, 51));
        sigTxt6.setForeground(Color.WHITE);
      
        if(sigB5.getBackground().equals(colorP)){
            sigB5.setBackground(Color.WHITE);
            sigTxt5.setForeground(new Color(0, 0, 51));
        }
        else if(sigB7.getBackground().equals(colorP)){
            sigB7.setBackground(Color.WHITE);
            sigTxt7.setForeground(new Color(0, 0, 51));
        }
        else if(sigB4.getBackground().equals(colorP)){
            sigB4.setBackground(Color.WHITE);
            sigTxt4.setForeground(new Color(0, 0, 51));
        }
        
    }//GEN-LAST:event_sigTxt6MouseClicked

    private void sigTxt7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sigTxt7MouseClicked
        
        sigB7.setBackground(new Color(0, 0, 51));
        sigTxt7.setForeground(Color.WHITE);
      
        if(sigB5.getBackground().equals(colorP)){
            sigB5.setBackground(Color.WHITE);
            sigTxt5.setForeground(new Color(0, 0, 51));
        }
        else if(sigB6.getBackground().equals(colorP)){
            sigB6.setBackground(Color.WHITE);
            sigTxt6.setForeground(new Color(0, 0, 51));
        }
        else if(sigB4.getBackground().equals(colorP)){
            sigB4.setBackground(Color.WHITE);
            sigTxt4.setForeground(new Color(0, 0, 51));
        }
        
    }//GEN-LAST:event_sigTxt7MouseClicked

    private void sigTxt4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sigTxt4MouseEntered
        if(!sigB4.getBackground().equals(colorP)){
            sigB4.setBackground(new Color(0x99, 0xCC, 0xFF));
        }
    }//GEN-LAST:event_sigTxt4MouseEntered

    private void sigTxt5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sigTxt5MouseEntered
        if(!sigB5.getBackground().equals(colorP)){
            sigB5.setBackground(new Color(0x99, 0xCC, 0xFF));
        }
    }//GEN-LAST:event_sigTxt5MouseEntered

    private void sigTxt6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sigTxt6MouseEntered
        if(!sigB6.getBackground().equals(colorP)){
            sigB6.setBackground(new Color(0x99, 0xCC, 0xFF));
        }
    }//GEN-LAST:event_sigTxt6MouseEntered

    private void sigTxt7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sigTxt7MouseEntered
        if(!sigB7.getBackground().equals(colorP)){
            sigB7.setBackground(new Color(0x99, 0xCC, 0xFF));
        }
    }//GEN-LAST:event_sigTxt7MouseEntered

    private void sigTxt4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sigTxt4MouseExited
        if(!sigB4.getBackground().equals(colorP)){
            sigB4.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_sigTxt4MouseExited

    private void sigTxt5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sigTxt5MouseExited
        if(!sigB5.getBackground().equals(colorP)){
            sigB5.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_sigTxt5MouseExited

    private void sigTxt6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sigTxt6MouseExited
        if(!sigB6.getBackground().equals(colorP)){
            sigB6.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_sigTxt6MouseExited

    private void sigTxt7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sigTxt7MouseExited
        if(!sigB7.getBackground().equals(colorP)){
            sigB7.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_sigTxt7MouseExited

    private void sigTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sigTxtMouseEntered
        sigTxt.setForeground(Color.WHITE);
        sigB.setBackground(new Color(0, 0, 51));
    }//GEN-LAST:event_sigTxtMouseEntered

    private void sigTxt3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sigTxt3MouseClicked
        this.dispose();
        form3 q3 = new form3();
        q3.setVisible(true);
    }//GEN-LAST:event_sigTxt3MouseClicked

    private void sigTxt3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sigTxt3MouseEntered
        sigTxt3.setForeground(Color.WHITE);
        sigB3.setBackground(new Color(0, 0, 51));
    }//GEN-LAST:event_sigTxt3MouseEntered

    private void sigTxt3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sigTxt3MouseExited
        sigTxt3.setForeground(new Color(0, 0, 51));
        sigB3.setBackground(Color.WHITE);
    }//GEN-LAST:event_sigTxt3MouseExited

    private void sigTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sigTxtMouseExited
        sigTxt.setForeground(new Color(0, 0, 51));
        sigB.setBackground(Color.WHITE);
    }//GEN-LAST:event_sigTxtMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel exitB;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel imgFondo;
    private javax.swing.JPanel navbar;
    private javax.swing.JLabel navbarTxt;
    private javax.swing.JPanel panelQ;
    private javax.swing.JLabel preguntaTxt;
    private javax.swing.JPanel sigB;
    private javax.swing.JPanel sigB3;
    private javax.swing.JPanel sigB4;
    private javax.swing.JPanel sigB5;
    private javax.swing.JPanel sigB6;
    private javax.swing.JPanel sigB7;
    private javax.swing.JLabel sigTxt;
    private javax.swing.JLabel sigTxt3;
    private javax.swing.JLabel sigTxt4;
    private javax.swing.JLabel sigTxt5;
    private javax.swing.JLabel sigTxt6;
    private javax.swing.JLabel sigTxt7;
    // End of variables declaration//GEN-END:variables
}
