/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import java.awt.Color;
import javax.swing.ImageIcon;
import main.Main;

/**
 *
 * @author Miguel
 */
public class perfilBanco extends javax.swing.JFrame {

    /**
     * Creates new form perfilBanco
     */
    public perfilBanco() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        cargarImagenes();
        cargarDatos();
    }
    
    public void cargarImagenes(){
        
        ImageIcon imgThisImg = new ImageIcon("C:\\Users\\Miguel\\Documents\\NetBeansProjects\\hipoteka\\src\\main\\java\\imagenes\\Picsart_24-02-28_19-12-02-305.jpg");
        imagenFondo.setIcon(imgThisImg);
    }
    
    public void cargarDatos(){
        
        textoBienv.setText(Main.getIntance().getBanco().getNombre());
        correo.setText(Main.getIntance().getBanco().getMail());
        telefono.setText(Main.getIntance().getBanco().getTelef());
        horario.setText(Main.getIntance().getBanco().getHorario());
        direccion.setText(Main.getIntance().getBanco().getDireccion());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        navbar = new javax.swing.JPanel();
        navbarTxt = new javax.swing.JLabel();
        exitB = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        bloqueInfo = new javax.swing.JPanel();
        textoBienv = new javax.swing.JLabel();
        correo = new javax.swing.JLabel();
        correoLabel = new javax.swing.JLabel();
        telefonoLabel = new javax.swing.JLabel();
        horarioLabel = new javax.swing.JLabel();
        direccionLabel = new javax.swing.JLabel();
        telefono = new javax.swing.JLabel();
        horario = new javax.swing.JLabel();
        direccion = new javax.swing.JLabel();
        cerrarSesion = new javax.swing.JPanel();
        cerrarSesionL = new javax.swing.JLabel();
        imagenFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1130, 628));
        setMinimumSize(new java.awt.Dimension(1130, 628));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1130, 628));
        setResizable(false);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navbar.setBackground(new java.awt.Color(0, 255, 153));
        navbar.setMaximumSize(new java.awt.Dimension(1130, 570));
        navbar.setPreferredSize(new java.awt.Dimension(1130, 72));

        navbarTxt.setFont(new java.awt.Font("Tw Cen MT", 0, 48)); // NOI18N
        navbarTxt.setForeground(new java.awt.Color(255, 255, 255));
        navbarTxt.setText("hipoteka");
        navbarTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        navbarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navbarTxtMouseClicked(evt);
            }
        });

        exitB.setBackground(new java.awt.Color(0, 255, 153));

        exitTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBLayout = new javax.swing.GroupLayout(exitB);
        exitB.setLayout(exitBLayout);
        exitBLayout.setHorizontalGroup(
            exitBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );
        exitBLayout.setVerticalGroup(
            exitBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
        navbar.setLayout(navbarLayout);
        navbarLayout.setHorizontalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(navbarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 791, Short.MAX_VALUE)
                .addComponent(exitB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        navbarLayout.setVerticalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(navbarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(navbarLayout.createSequentialGroup()
                .addComponent(exitB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        fondo.add(navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bloqueInfo.setBackground(new java.awt.Color(255, 255, 255));
        bloqueInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoBienv.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        bloqueInfo.add(textoBienv, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 6, 450, 70));

        correo.setMaximumSize(new java.awt.Dimension(300, 33));
        bloqueInfo.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 105, 300, 33));

        correoLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        correoLabel.setText("Correo electrónico:");
        bloqueInfo.add(correoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 113, -1, -1));

        telefonoLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        telefonoLabel.setText("Teléfono:");
        bloqueInfo.add(telefonoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 159, 55, -1));

        horarioLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        horarioLabel.setText("Horario:");
        bloqueInfo.add(horarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        direccionLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        direccionLabel.setText("Dirección:");
        bloqueInfo.add(direccionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        telefono.setMaximumSize(new java.awt.Dimension(300, 33));
        bloqueInfo.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 152, 300, 30));

        horario.setMaximumSize(new java.awt.Dimension(300, 33));
        bloqueInfo.add(horario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 202, 300, 33));

        direccion.setMaximumSize(new java.awt.Dimension(300, 33));
        bloqueInfo.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 252, 300, 33));

        cerrarSesion.setBackground(new java.awt.Color(255, 255, 255));

        cerrarSesionL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cerrarSesionL.setForeground(new java.awt.Color(255, 0, 0));
        cerrarSesionL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrarSesionL.setText("Cerrar sesión");
        cerrarSesionL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        cerrarSesionL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarSesionLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarSesionLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarSesionLMouseExited(evt);
            }
        });

        javax.swing.GroupLayout cerrarSesionLayout = new javax.swing.GroupLayout(cerrarSesion);
        cerrarSesion.setLayout(cerrarSesionLayout);
        cerrarSesionLayout.setHorizontalGroup(
            cerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cerrarSesionL, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        cerrarSesionLayout.setVerticalGroup(
            cerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cerrarSesionL, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bloqueInfo.add(cerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, -1));

        fondo.add(bloqueInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 480, 370));
        fondo.add(imagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 72, 1130, 562));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void navbarTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navbarTxtMouseClicked
        vPBanco vPB = new vPBanco();
        vPB.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_navbarTxtMouseClicked

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitB.setBackground(Color.RED);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitB.setBackground(new Color(0, 255, 153));
    }//GEN-LAST:event_exitTxtMouseExited

    private void cerrarSesionLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionLMouseEntered
        cerrarSesion.setBackground(new Color(255, 0, 0));
        cerrarSesionL.setForeground(Color.WHITE);
    }//GEN-LAST:event_cerrarSesionLMouseEntered

    private void cerrarSesionLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionLMouseExited
        cerrarSesion.setBackground(Color.WHITE);
        cerrarSesionL.setForeground(new Color(255, 0, 0));
    }//GEN-LAST:event_cerrarSesionLMouseExited

    private void cerrarSesionLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionLMouseClicked
        Main.getIntance().setBancoActivo(null);
        this.dispose();
        
        Home home = new Home();
        home.setVisible(true);
    }//GEN-LAST:event_cerrarSesionLMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(perfilBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(perfilBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(perfilBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(perfilBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new perfilBanco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bloqueInfo;
    private javax.swing.JPanel cerrarSesion;
    private javax.swing.JLabel cerrarSesionL;
    private javax.swing.JLabel correo;
    private javax.swing.JLabel correoLabel;
    private javax.swing.JLabel direccion;
    private javax.swing.JLabel direccionLabel;
    private javax.swing.JPanel exitB;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel horario;
    private javax.swing.JLabel horarioLabel;
    private javax.swing.JLabel imagenFondo;
    private javax.swing.JPanel navbar;
    private javax.swing.JLabel navbarTxt;
    private javax.swing.JLabel telefono;
    private javax.swing.JLabel telefonoLabel;
    private javax.swing.JLabel textoBienv;
    // End of variables declaration//GEN-END:variables
}
